version: '3'
services:
    mongodb:
      container_name: mongodb-exchange
      image: mongo:latest
      ports:
          - 27017:27017

    redis:
      container_name: redis-exchange
      image: redis:4.0.6
      ports:
        - 6379:6379
      environment:
        - REDIS_URI: redis://redis:6379
      links:
        - mongodb

    app:
      build: .
      command: yarn start
      ports:
          - 4000:4000
      environment: 
          PORT: 4000
          MONGO_URI: mongodb://mongodb:27017
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      links:
          - mongodb
      depends_on: 
          - mongodb
          - redis
volumes:
  nodemodules: {}

