version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - data:/data/db
    ports:
      - 27018:27017
    networks:
      - my-network

  redis:
    container_name: redis
    image: redis:4.0.6
    ports:
      - 6379:6379
    links:
      - mongodb
    networks:
      - my-network
  
  currency:
    build: .
    container_name: currency
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    environment:
      PORT: 3000
    depends_on:
      - redis
      - mongodb
    links:
      - mongodb
      - redis
    networks:
      - my-network

volumes:
  data: {}
networks:
  my-network: