version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - data:/data/db
    ports:
      - 27018:27017
  
  currency:
    build: .
    container_name: currency
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    environment:
      PORT: 3000
    links:
      - mongodb
    depends_on:
      - mongodb

volumes:
  data: {}